package org.jukeboxmc.world

import org.cloudburstmc.protocol.bedrock.data.LevelEvent
import org.cloudburstmc.protocol.bedrock.data.LevelEventType
import org.cloudburstmc.protocol.bedrock.data.ParticleType

/**
 * @author LucGamesYT
 * @version 1.0
 */
enum class Particle(val type: LevelEventType) {
    SHOOT(LevelEvent.PARTICLE_SHOOT), DESTROY_BLOCK(LevelEvent.PARTICLE_DESTROY_BLOCK), POTION_SPLASH(
        LevelEvent.PARTICLE_POTION_SPLASH,
    ),
    EYE_OF_ENDER_DEATH(LevelEvent.PARTICLE_EYE_OF_ENDER_DEATH), MOB_BLOCK_SPAWN(LevelEvent.PARTICLE_MOB_BLOCK_SPAWN), CROP_GROWTH(
        LevelEvent.PARTICLE_CROP_GROWTH,
    ),
    SOUND_GUARDIAN_GHOST(LevelEvent.PARTICLE_SOUND_GUARDIAN_GHOST), DEATH_SMOKE(LevelEvent.PARTICLE_DEATH_SMOKE), DENY_BLOCK(
        LevelEvent.PARTICLE_DENY_BLOCK,
    ),
    GENERIC_SPAWN(LevelEvent.PARTICLE_GENERIC_SPAWN), DRAGON_EGG(LevelEvent.PARTICLE_DRAGON_EGG), CROP_EATEN(
        LevelEvent.PARTICLE_CROP_EATEN,
    ),
    CRIT(LevelEvent.PARTICLE_CRIT), TELEPORT(LevelEvent.PARTICLE_TELEPORT), CRACK_BLOCK(LevelEvent.PARTICLE_CRACK_BLOCK), BUBBLES(
        LevelEvent.PARTICLE_BUBBLES,
    ),
    EVAPORATE(LevelEvent.PARTICLE_EVAPORATE), DESTROY_ARMOR_STAND(LevelEvent.PARTICLE_DESTROY_ARMOR_STAND), BREAKING_EGG(
        LevelEvent.PARTICLE_BREAKING_EGG,
    ),
    DESTROY_EGG(LevelEvent.PARTICLE_DESTROY_EGG), EVAPORATE_WATER(LevelEvent.PARTICLE_EVAPORATE_WATER), DESTROY_BLOCK_NO_SOUND(
        LevelEvent.PARTICLE_DESTROY_BLOCK_NO_SOUND,
    ),
    KNOCKBACK_ROAR(LevelEvent.PARTICLE_KNOCKBACK_ROAR), TELEPORT_TRAIL(LevelEvent.PARTICLE_TELEPORT_TRAIL), POINT_CLOUD(
        LevelEvent.PARTICLE_POINT_CLOUD,
    ),
    EXPLOSION(LevelEvent.PARTICLE_EXPLOSION), BLOCK_EXPLOSION(LevelEvent.PARTICLE_BLOCK_EXPLOSION), DRIPSTONE_DRIP(
        LevelEvent.PARTICLE_DRIPSTONE_DRIP,
    ),
    FIZZ_EFFECT(LevelEvent.PARTICLE_FIZZ_EFFECT), WAX_ON(LevelEvent.PARTICLE_WAX_ON), WAX_OFF(LevelEvent.PARTICLE_WAX_OFF), SCRAPE(
        LevelEvent.PARTICLE_SCRAPE,
    ),
    BUBBLE(ParticleType.BUBBLE), BUBBLE_MANUAL(ParticleType.BUBBLE_MANUAL), CRITICAL(
        ParticleType.CRIT,
    ),
    BLOCK_FORCE_FIELD(ParticleType.BLOCK_FORCE_FIELD), SMOKE(ParticleType.SMOKE), EXPLODE(
        ParticleType.EXPLODE,
    ),
    EVAPORATION(ParticleType.EVAPORATION), FLAME(ParticleType.FLAME), CANDLE_FLAME(ParticleType.CANDLE_FLAME), LAVA(
        ParticleType.LAVA,
    ),
    LARGE_SMOKE(ParticleType.LARGE_SMOKE), REDSTONE(ParticleType.SCULK_SENSOR_REDSTONE), RISING_RED_DUST(
        ParticleType.RED_DUST,
    ),
    ITEM_BREAK(LevelEvent.PARTICLE_DESTROY_BLOCK), SNOWBALL_POOF(ParticleType.SNOWBALL_POOF), HUGE_EXPLODE(
        ParticleType.HUGE_EXPLOSION,
    ),
    HUGE_EXPLODE_SEED(ParticleType.LARGE_EXPLODE), MOB_FLAME(ParticleType.MOB_FLAME), HEART(
        ParticleType.HEART,
    ),
    TERRAIN(ParticleType.TERRAIN), TOWN_AURA(ParticleType.TOWN_AURA), PORTAL(ParticleType.PORTAL), MOB_PORTAL(
        ParticleType.MOB_PORTAL,
    ),
    SPLASH(ParticleType.WATER_SPLASH), SPLASH_MANUAL(ParticleType.WATER_SPLASH_MANUAL), WATER_WAKE(
        ParticleType.WATER_WAKE,
    ),
    DRIP_WATER(ParticleType.DRIP_WATER), DRIP_LAVA(ParticleType.DRIP_LAVA), DRIP_HONEY(
        ParticleType.DRIP_HONEY,
    ),
    STALACTITE_DRIP_WATER(ParticleType.STALACTITE_DRIP_WATER), STALACTITE_DRIP_LAVA(ParticleType.STALACTITE_DRIP_LAVA), FALLING_DUST(
        ParticleType.FALLING_DUST,
    ),
    MOB_SPELL(ParticleType.MOB_SPELL), MOB_SPELL_AMBIENT(ParticleType.MOB_SPELL_AMBIENT), MOB_SPELL_INSTANTANEOUS(
        ParticleType.MOB_SPELL_INSTANTANEOUS,
    ),
    INK(ParticleType.INK), SLIME(ParticleType.SLIME), RAIN_SPLASH(ParticleType.RAIN_SPLASH), VILLAGER_ANGRY(
        ParticleType.VILLAGER_ANGRY,
    ),
    VILLAGER_HAPPY(ParticleType.VILLAGER_HAPPY), ENCHANTMENT_TABLE(ParticleType.ENCHANTING_TABLE), TRACKING_EMITTER(
        ParticleType.TRACKER_EMITTER,
    ),
    NOTE(ParticleType.NOTE), WITCH_SPELL(ParticleType.WITCH_SPELL), CARROT(ParticleType.CARROT_BOOST), MOB_APPEARANCE(
        ParticleType.MOB_APPEARANCE,
    ),
    END_ROD(ParticleType.END_ROD), SPIT(ParticleType.SPIT), TOTEM(ParticleType.TOTEM), FOOD(
        ParticleType.FOOD,
    ),
    FIREWORKS_STARTER(ParticleType.FIREWORKS_STARTER), FIREWORKS_SPARK(ParticleType.FIREWORKS), FIREWORKS_OVERLAY(
        ParticleType.FIREWORKS_OVERLAY,
    ),
    BALLOON_GAS(ParticleType.BALLOON_GAS), COLORED_FLAME(ParticleType.COLORED_FLAME), SPARKLER(
        ParticleType.SPARKLER,
    ),
    CONDUIT(ParticleType.CONDUIT), BUBBLE_COLUMN_UP(ParticleType.BUBBLE_COLUMN_UP), BUBBLE_COLUMN_DOWN(
        ParticleType.BUBBLE_COLUMN_DOWN,
    ),
    SNEEZE(ParticleType.SNEEZE), SHULKER_BULLET(ParticleType.SHULKER_BULLET), BLEACH(
        ParticleType.BLEACH,
    ),
    DRAGON_DESTROY_BLOCK(ParticleType.DRAGON_DESTROY_BLOCK), MYCELIUM_DUST(ParticleType.MYCELIUM_DUST), FALLING_RED_DUST(
        ParticleType.FALLING_DUST,
    ),
    CAMPFIRE_SMOKE(ParticleType.CAMPFIRE_SMOKE), TALL_CAMPFIRE_SMOKE(ParticleType.CAMPFIRE_SMOKE_TALL), RISING_DRAGONS_BREATH(
        ParticleType.DRAGON_BREATH_FIRE,
    ),
    DRAGONS_BREATH(ParticleType.DRAGON_BREATH), BLUE_FLAME(ParticleType.BLUE_FLAME), SOUL(
        ParticleType.SOUL,
    ),
    OBSIDIAN_TEAR(ParticleType.OBSIDIAN_TEAR), PORTAL_REVERSE(ParticleType.PORTAL_REVERSE), SNOWFLAKE(
        ParticleType.SNOWFLAKE,
    ),
    VIBRATION_SIGNAL(ParticleType.VIBRATION_SIGNAL), SCULK_SENSOR_REDSTONE(ParticleType.SCULK_SENSOR_REDSTONE), SPORE_BLOSSOM_SHOWER(
        ParticleType.SPORE_BLOSSOM_SHOWER,
    ),
    SPORE_BLOSSOM_AMBIENT(ParticleType.SPORE_BLOSSOM_AMBIENT), WAX(ParticleType.WAX), ELECTRIC_SPARK(
        ParticleType.ELECTRIC_SPARK,
    )
}
