name: build

on:
  - push
  - pull_request
jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Add permission to gradlew
        run: chmod +x gradlew
      - name: Restore Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
          key: "gradle-cache-${{ matrix.java }}"
          restore-keys: |
            gradle-cache-${{ matrix.java }}-
      - name: Build jar
        run: ./gradlew build